version: '3.8'

services:
  backend:
    build: ./backend
    container_name: skbc-backend
    volumes:
      - ./backend/data:/app/data
      - ./backend/uploads:/app/uploads
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"
    restart: always

  frontend:
    build: ./frontend
    container_name: skbc-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always
